### ISSUE TITLE
To-do for Release

### ISSUE THREAD

**Issue by kermeow** [kermeow/gaml#1]
- [x] Installation flow
	- [x] Create required files
	- [x] Generate configurations
		- [x] Replace autoloads
- [x] Mod system
	- [x] Mod info (id, name, etc.)
	- [x] Versioning system
	- [x] Logging
	- [x] Dependencies
	- [x] Export plugin
- [x] Mod loading flow
	- [x] "Inject" mod loader (via bootstrapper)
	- [x] Load & verify mods
		- [x] GAML mods
		- [x] Asset mods
	- [x] Initialise mods
	- [x] Load game
- [x] Harmony-esque hooking library
	- [x] "Injection" for non-autoloads
	- [x] Prefixes
	- [x] Postfixes
	- [x] Support special methods (_ready, _process, etc)
	- [x] Result replacement

**Comment by kermeow** [comment]
After a few hours of work, GAML is ready for release.
